// Comprehensive unit tests for Telomere AI
import { SNP_DATABASE, SNP_MAP, lookupSnp, getByCategory, matchSnps, getCategories } from '../packages/snp-db/src/index.js';
import { parseGeneticFile, detectFormatByExtension, shouldUseStreaming } from '../packages/parsers/src/index.js';
import { calculatePGS, calculateAllPGS, PGS_SCORES } from '../packages/pgs/src/index.js';

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    passed++;
    console.log(`  ✅ ${name}`);
  } catch (e) {
    failed++;
    console.log(`  ❌ ${name}: ${e.message}`);
  }
}

function assert(cond, msg) {
  if (!cond) throw new Error(msg || 'Assertion failed');
}

// ========================================
console.log('\n=== 1. SNP Database ===');
// ========================================

test('loads 378 SNPs', () => {
  assert(SNP_DATABASE.length === 378, `Got ${SNP_DATABASE.length}`);
});

test('Map size matches array', () => {
  assert(SNP_MAP.size === SNP_DATABASE.length);
});

test('lookupSnp finds rs429358 (APOE)', () => {
  const snp = lookupSnp('rs429358');
  assert(snp !== null && snp !== undefined);
  assert(snp.gene === 'APOE', `Gene was ${snp.gene}`);
});

test('lookupSnp returns null for non-existent', () => {
  const snp = lookupSnp('rs999999999');
  assert(snp === undefined || snp === null);
});

test('6 categories exist', () => {
  const cats = getCategories();
  assert(cats.length === 6, `Got ${cats.length}`);
  for (const c of ['health', 'pharma', 'nutrition', 'traits', 'longevity', 'carrier']) {
    assert(cats.includes(c), `Missing category: ${c}`);
  }
});

test('each category has SNPs', () => {
  for (const c of getCategories()) {
    const snps = getByCategory(c);
    assert(snps.length > 0, `${c} has 0 SNPs`);
  }
});

test('every SNP has required fields', () => {
  for (const snp of SNP_DATABASE) {
    assert(snp.rsid, `Missing rsid`);
    assert(snp.gene, `${snp.rsid} missing gene`);
    assert(snp.riskAllele, `${snp.rsid} missing riskAllele`);
    assert(snp.categories && snp.categories.length > 0, `${snp.rsid} missing categories`);
  }
});

test('matchSnps returns correct results', () => {
  const userSnps = new Map([
    ['rs429358', { genotype: 'CT', allele1: 'C', allele2: 'T', chromosome: '19', position: 44908684 }],
    ['rs7412', { genotype: 'CC', allele1: 'C', allele2: 'C', chromosome: '19', position: 44908822 }],
    ['rs_fake_not_in_db', { genotype: 'AA', allele1: 'A', allele2: 'A' }],
  ]);
  const results = matchSnps(userSnps);
  assert(results.length === 2, `Expected 2 matches, got ${results.length}`);
  assert(results.every(r => r.riskLevel), 'All results should have riskLevel');
  assert(results.every(r => r.userGenotype), 'All results should have userGenotype');
});

// ========================================
console.log('\n=== 2. Parsers ===');
// ========================================

test('23andMe format parsed correctly', () => {
  const data = [
    '# This data file generated by 23andMe',
    '# rsid\tchromosome\tposition\tgenotype',
    'rs4477212\t1\t82154\tAA',
    'rs3094315\t1\t752566\tAG',
    'rs3131972\t1\t752721\tGG',
  ].join('\n');
  const r = parseGeneticFile(data);
  assert(r.format === 'twentythree', `Format was ${r.format}`);
  assert(r.snps.size === 3, `Got ${r.snps.size} SNPs`);
  const snp = r.snps.get('rs4477212');
  assert(snp.genotype === 'AA');
  assert(snp.chromosome === '1');
});

test('AncestryDNA format parsed correctly', () => {
  const data = [
    'AncestryDNA raw data download',
    '#rsid\tchromosome\tposition\tallele1\tallele2',
    'rs4477212\t1\t82154\tA\tA',
    'rs3094315\t1\t752566\tA\tG',
  ].join('\n');
  const r = parseGeneticFile(data);
  assert(r.format === 'ancestry', `Format was ${r.format}`);
  assert(r.snps.size === 2);
  const snp = r.snps.get('rs4477212');
  assert(snp.allele1 === 'A');
  assert(snp.allele2 === 'A');
});

test('MyHeritage format parsed correctly', () => {
  const data = [
    '##MyHeritage DNA raw data',
    '##This file contains raw genotype data',
    'RSID,CHROMOSOME,POSITION,RESULT',
    '"rs4477212","1","82154","AA"',
    '"rs3094315","1","752566","AG"',
  ].join('\n');
  const r = parseGeneticFile(data);
  assert(r.format === 'myheritage', `Format was ${r.format}`);
  assert(r.snps.size === 2);
});

test('VCF format parsed correctly', () => {
  const data = [
    '##fileformat=VCFv4.1',
    '##source=test',
    '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE',
    '1\t82154\trs4477212\tG\tA\t.\tPASS\t.\tGT\t1/1',
    '1\t752566\trs3094315\tA\tG\t.\tPASS\t.\tGT\t0/1',
    '1\t752721\trs3131972\tA\tG\t.\tPASS\t.\tGT\t1/1',
  ].join('\n');
  const r = parseGeneticFile(data);
  assert(r.format === 'vcf', `Format was ${r.format}`);
  assert(r.snps.size === 3);
  const snp = r.snps.get('rs4477212');
  assert(snp.genotype === 'AA', `Genotype was ${snp.genotype}`);
});

test('unknown format throws', () => {
  try {
    parseGeneticFile('just some random text\nwith no structure');
    assert(false, 'Should have thrown');
  } catch (e) {
    assert(e.message.includes('Unable to detect'), `Wrong error: ${e.message}`);
  }
});

test('format detection by extension', () => {
  assert(detectFormatByExtension('data.vcf') === 'vcf');
  assert(detectFormatByExtension('data.vcf.gz') === 'vcf');
  assert(detectFormatByExtension('data.bgz') === 'vcf');
  assert(detectFormatByExtension('data.txt') === null);
  assert(detectFormatByExtension('data.csv') === null);
});

test('streaming threshold', () => {
  assert(shouldUseStreaming({ size: 100, name: 'test.txt' }) === false);
  assert(shouldUseStreaming({ size: 100, name: 'test.vcf.gz' }) === true);
  assert(shouldUseStreaming({ size: 60 * 1024 * 1024, name: 'big.txt' }) === true);
});

// ========================================
console.log('\n=== 3. Polygenic Risk Scores ===');
// ========================================

test('PGS_SCORES has entries', () => {
  const ids = Object.keys(PGS_SCORES);
  assert(ids.length >= 5, `Only ${ids.length} PGS scores`);
});

test('each PGS has required fields', () => {
  for (const [id, score] of Object.entries(PGS_SCORES)) {
    assert(score.trait, `${id} missing trait`);
    assert(score.category, `${id} missing category`);
    assert(score.variants && score.variants.length > 0, `${id} has no variants`);
    for (const v of score.variants) {
      assert(v.rsid, `${id} variant missing rsid`);
      assert(v.effectAllele, `${id} ${v.rsid} missing effectAllele`);
      assert(typeof v.weight === 'number', `${id} ${v.rsid} weight not number`);
    }
  }
});

test('calculatePGS with matching SNPs', () => {
  const cadVariants = PGS_SCORES['PGS000001'].variants;
  const userSnps = new Map();
  // Add 5 SNPs from CAD scoring
  for (const v of cadVariants.slice(0, 5)) {
    userSnps.set(v.rsid, { genotype: v.effectAllele + v.effectAllele, allele1: v.effectAllele, allele2: v.effectAllele });
  }
  const result = calculatePGS(userSnps, cadVariants);
  assert(result.matched === 5, `Matched ${result.matched}, expected 5`);
  assert(result.total === cadVariants.length);
  assert(typeof result.score === 'number');
  assert(result.score > 0, 'Score should be positive with homozygous effect alleles');
});

test('calculatePGS with no matching SNPs', () => {
  const userSnps = new Map([['rs_fake', { genotype: 'AA', allele1: 'A', allele2: 'A' }]]);
  const result = calculatePGS(userSnps, PGS_SCORES['PGS000001'].variants);
  assert(result.matched === 0);
  assert(result.score === 0);
});

test('calculateAllPGS returns all scores', () => {
  // Build a user SNP map from sample genome data
  const userSnps = new Map([
    ['rs10455872', { genotype: 'AG', allele1: 'A', allele2: 'G' }],
    ['rs4977574', { genotype: 'GG', allele1: 'G', allele2: 'G' }],
    ['rs7756992', { genotype: 'GG', allele1: 'G', allele2: 'G' }],
    ['rs5219', { genotype: 'CT', allele1: 'C', allele2: 'T' }],
    ['rs9939609', { genotype: 'AT', allele1: 'A', allele2: 'T' }],
  ]);
  const results = calculateAllPGS(userSnps);
  assert(results.length === Object.keys(PGS_SCORES).length);
  assert(results.every(r => typeof r.percentile === 'number'));
  assert(results.every(r => r.percentile >= 0 && r.percentile <= 100));
  const cad = results.find(r => r.id === 'PGS000001');
  assert(cad && cad.variantsUsed >= 1, 'CAD should match at least 1 variant');
});

// ========================================
console.log('\n=== 4. End-to-End: Parse → Match → Analyze ===');
// ========================================

test('full pipeline: 23andMe file → matched SNPs → traits', async () => {
  // Simulate a real 23andMe file with known SNPs from our database
  const knownSnps = SNP_DATABASE.slice(0, 50);
  const lines = ['# This data file generated by 23andMe', '# rsid\tchromosome\tposition\tgenotype'];
  for (const snp of knownSnps) {
    // Use risk allele homozygous for some, normal for others
    const geno = Math.random() > 0.5 ? snp.riskAllele + snp.riskAllele : snp.normalAllele + snp.normalAllele;
    lines.push(`${snp.rsid}\t${snp.chromosome || '1'}\t${snp.position || 100000}\t${geno}`);
  }
  
  // Parse
  const parsed = parseGeneticFile(lines.join('\n'));
  assert(parsed.snps.size === 50, `Parsed ${parsed.snps.size} SNPs`);
  
  // Match against database
  const matched = matchSnps(parsed.snps);
  assert(matched.length === 50, `Matched ${matched.length} SNPs`);
  
  // Check risk levels assigned
  const riskLevels = new Set(matched.map(m => m.riskLevel));
  assert(riskLevels.size >= 2, 'Should have at least 2 different risk levels');
  
  // Calculate PGS
  const pgsResults = calculateAllPGS(parsed.snps);
  assert(pgsResults.length > 0, 'Should have PGS results');
});

test('full pipeline: sample genome data', () => {
  // Build sample genome inline (matching the app's sample-genome.js structure)
  const SAMPLE_GENOME = { name: 'Test', snps: new Map() };
  // Add first 100 known SNPs from our DB as test data
  for (const snp of SNP_DATABASE.slice(0, 100)) {
    const geno = Math.random() > 0.3 ? snp.riskAllele + snp.riskAllele : (snp.normalAllele || 'A') + (snp.normalAllele || 'A');
    SAMPLE_GENOME.snps.set(snp.rsid, { genotype: geno, allele1: geno[0], allele2: geno[1], chromosome: snp.chromosome || '1', position: snp.position || 0 });
  }
  assert(SAMPLE_GENOME.snps instanceof Map, 'Sample genome should have Map of SNPs');
  assert(SAMPLE_GENOME.snps.size >= 80, `Only ${SAMPLE_GENOME.snps.size} sample SNPs`);
  
  // Match
  const matched = matchSnps(SAMPLE_GENOME.snps);
  assert(matched.length > 50, `Only matched ${matched.length} SNPs`);
  
  // Verify risk distribution
  const high = matched.filter(m => m.riskLevel === 'high').length;
  const moderate = matched.filter(m => m.riskLevel === 'moderate').length;
  const low = matched.filter(m => m.riskLevel === 'low').length;
  console.log(`    Risk distribution: ${high} high, ${moderate} moderate, ${low} low`);
  assert(high > 0, 'Should have some high risk');
  assert(moderate > 0, 'Should have some moderate risk');
  assert(low > 0, 'Should have some low risk');
  
  // PGS
  const pgsResults = calculateAllPGS(SAMPLE_GENOME.snps);
  const withMatches = pgsResults.filter(r => r.variantsUsed > 0);
  assert(withMatches.length > 0, 'Should have PGS with matched variants');
  console.log(`    PGS: ${withMatches.length}/${pgsResults.length} scores with data`);
});

// ========================================
console.log('\n=== 5. Trait Builder ===');
// ========================================

test('buildTraits groups SNPs correctly', () => {
  // Import trait builder (ESM compat)
  // Can't import ESM from CJS easily, so test the logic inline
  const matched = matchSnps(new Map([
    ['rs429358', { genotype: 'CT', allele1: 'C', allele2: 'T', chromosome: '19', position: 44908684 }],
    ['rs7412', { genotype: 'CC', allele1: 'C', allele2: 'C', chromosome: '19', position: 44908822 }],
    ['rs4420638', { genotype: 'AG', allele1: 'A', allele2: 'G', chromosome: '19', position: 45422946 }],
    ['rs769449', { genotype: 'AG', allele1: 'A', allele2: 'G', chromosome: '19', position: 44905579 }],
  ]));
  assert(matched.length === 4, `Matched ${matched.length}`);
  // Check that APOE-related SNPs share conditions
  const withAlzheimer = matched.filter(m => 
    m.conditions && m.conditions.some(c => c.toLowerCase().includes('alzheimer'))
  );
  assert(withAlzheimer.length >= 1, 'APOE SNPs should mention Alzheimer');
});

// ========================================
// Summary
// ========================================
console.log(`\n${'='.repeat(40)}`);
console.log(`Results: ${passed} passed, ${failed} failed`);
console.log(`${'='.repeat(40)}\n`);

if (failed > 0) process.exit(1);
